const SUPABASE_URL="https://hogbjrbaeedlyglegjle.supabase.co";const SUPABASE_KEY="sb_publishable_NWG23rPztabdaFhEyNtN5w_rrCeMTC5";const {createClient}=window.supabase;const db=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const houseMeta={Pegaso:{e:"🪽",c:"#e7dfc6",g:"rgba(231,223,198,.45)"},Cronos:{e:"⏳",c:"#4aaeff",g:"rgba(74,174,255,.45)"},Fénix:{e:"🔥",c:"#e0b54f",g:"rgba(224,181,79,.45)"},Argos:{e:"👁️",c:"#5fd69a",g:"rgba(95,214,154,.45)"},Olimpo:{e:"⚡",c:"#e46e78",g:"rgba(228,110,120,.45)"}};
let current=null,member=null,directivaMode=false;
function message(t,ok=false){const el=$("#authMessage");el.textContent=t;el.style.color=ok?"#6fe0a3":"#e7c26a"}
function setMode(mode){document.querySelectorAll(".auth-tab").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));$("#signupPanel").hidden=mode!=="signup";$("#loginPanel").hidden=mode!=="login";message("")}
document.querySelectorAll(".auth-tab").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));
$("#signupForm").addEventListener("submit",async e=>{e.preventDefault();const email=$("#signupEmail").value.trim();const p=$("#signupPassword").value;const p2=$("#signupPassword2").value;if(p!==p2)return message("Las contraseñas no coinciden.");if(p.length<8)return message("La contraseña debe tener al menos 8 caracteres.");message("Comprobando tu aprobación…");const {data,error}=await db.rpc("verificar_integrante_aprobado",{p_email:email});if(error)return message("No pudimos comprobar tu registro. Inténtalo nuevamente.");if(!data?.ok){const map={not_found:"Ese correo no aparece entre los integrantes aprobados.",inactive:"Tu registro está inactivo. Consulta con Directiva.",already_linked:"Este integrante ya tiene una cuenta. Usa Iniciar sesión."};return message(map[data.reason]||"Tu registro todavía no está habilitado.");}message("Registro aprobado. Creando tu acceso…",true);const {data:sign,error:signErr}=await db.auth.signUp({email,password:p,options:{emailRedirectTo:location.origin}});if(signErr){if(/already registered|already been registered/i.test(signErr.message))return message("Este correo ya tiene una cuenta. Usa Iniciar sesión.");return message(signErr.message)}localStorage.setItem("nova_pending_integrante",data.integrante_id);if(sign.session){const {data:linked,error:linkErr}=await db.rpc("vincular_cuenta_integrante",{p_integrante_id:data.integrante_id});if(linkErr||!linked)return message("La cuenta se creó, pero no pudimos vincularla todavía. Inicia sesión para terminar.");message("¡Cuenta creada! Entrando a NOVA…",true);await boot()}else{message("Cuenta creada. Revisa tu correo para confirmar la cuenta y luego inicia sesión.",true);setMode("login");$("#loginEmail").value=email}});
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();message("Verificando acceso…");const email=$("#loginEmail").value.trim();const {error}=await db.auth.signInWithPassword({email,password:$("#loginPassword").value});if(error)return message("Correo o contraseña incorrectos.");const pending=localStorage.getItem("nova_pending_integrante");if(pending){try{await db.rpc("vincular_cuenta_integrante",{p_integrante_id:pending})}catch(_){}localStorage.removeItem("nova_pending_integrante")}await boot()});
$("#resetBtn").addEventListener("click",async()=>{const email=$("#loginEmail").value.trim();if(!email)return message("Escribe tu correo primero.");const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin});message(error?"No pudimos enviar el enlace.": "Te enviamos un enlace para restablecer tu contraseña.",!error)});
$("#logoutBtn").addEventListener("click",async()=>{await db.auth.signOut();location.reload()});
async function boot(){const {data:{user}}=await db.auth.getUser();if(!user){$("#authView").hidden=false;$("#dashboardView").hidden=true;return}
directivaMode=false;
const {data:m,error}=await db.from("integrantes").select("*").eq("user_id",user.id).maybeSingle();if(error||!m){await db.auth.signOut();message("Tu cuenta todavía no está vinculada a un integrante aprobado.");return}member=m;current=user;$("#authView").hidden=true;$("#dashboardView").hidden=false;await Promise.all([loadProfile(),loadHouses(),loadAreas(),loadActivities(),loadFeedback(),loadAchievements()]);subscribeRealtime()}
async function loadProfile(){const initials=member.nombre_completo.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase();$("#topAvatar").textContent=initials;$("#topName").textContent=member.nombre_completo;$("#heroName").textContent=member.nombre_completo.split(" ")[0];$("#profileName").textContent=member.nombre_completo;$("#topRole").textContent=member.username?"@"+member.username:"NOVA MEMBER";$("#profileUsername").textContent=member.username?"@"+member.username:"@nova";$("#profileCourse").textContent=(member.curso||"NOVA")+" · "+(member.seccion||"");const {data:house}=await db.from("casas").select("*").eq("id",member.casa_id).maybeSingle();renderHouseBadge(house)}
function renderHouseBadge(h){const el=$("#houseBadge");if(!h){el.innerHTML="<span>✦</span><div><small>CASA</small><strong>Asignación pendiente</strong></div>";return}const x=houseMeta[h.nombre]||{e:"✦",c:"#9db0c8",g:"rgba(157,176,200,.25)"};el.style.borderColor=x.c;el.innerHTML=`<span>${x.e}</span><div><small>TU CASA</small><strong>${esc(h.nombre)}</strong></div>`}
async function loadHouses(){const {data}=await db.from("casas").select("*").order("puntos",{ascending:false});const list=data||[];const mine=member?.casa_id;$("#houseBoard").innerHTML=list.map((h,i)=>{const x=houseMeta[h.nombre]||{e:h.emblema||"✦",c:"#9db0c8",g:"rgba(157,176,200,.25)"};return `<article class="house-tile ${h.id===mine?"mine":""}" style="--house-color:${x.c};--house-glow:${x.g};--house-line:${x.c}55;--house-soft:${x.g.replace("0.45","0.08")}"><div class="house-rank">#${i+1}</div><div class="house-emblem">${x.e}</div><div class="house-name">${esc(h.nombre)}</div><div class="house-points" data-points="${h.puntos||0}">${h.puntos||0}<small> PTS</small></div></article>`}).join("")}
async function loadAreas(){const {data:areas}=await db.from("integrante_areas").select("*").eq("integrante_id",member.id).order("area");const a=areas||[];$("#areaChips").innerHTML=a.length?a.map(x=>`<span>${areaIcon(x.area)} ${esc(x.area)}</span>`).join(""):"<span>Miembro NOVA</span>";$("#areaSection").hidden=!a.length;const {data:mun}=await db.from("mun_asignaciones").select("*").eq("integrante_id",member.id).maybeSingle();const {data:debate}=await db.from("debate_tripletas").select("*").eq("integrante_id",member.id).maybeSingle();const {data:staff}=await db.from("staff_asignaciones").select("*").eq("integrante_id",member.id).maybeSingle();$("#areaModules").innerHTML=a.map(x=>moduleFor(x.area,{mun,debate,staff,x})).join("");$("#timeline").innerHTML=[`<div class="timeline-item"><strong>Integrante aprobado</strong>${member.fecha_aprobacion?new Date(member.fecha_aprobacion).toLocaleDateString("es-DO"):"Dentro de NOVA"}</div>`,...a.slice(0,3).map(x=>`<div class="timeline-item"><strong>${areaIcon(x.area)} ${esc(x.area)}</strong>Área activa dentro del club</div>`)].join("")}
function areaIcon(a){return {"Artística":"🎨","MUN / ONU":"🌐","Debate":"⚔️","Oratoria":"🎙️","Staff":"⚙️"}[a]||"✦"}
function moduleFor(area,d){let rows="";if(area==="MUN / ONU"&&d.mun)rows=`<div class="data-row"><span>País</span><b>${esc(d.mun.pais||"Por asignar")}</b></div><div class="data-row"><span>Comisión</span><b>${esc(d.mun.comision||"Por asignar")}</b></div>`;if(area==="Debate"&&d.debate){const names=d.debate.companeros?.length?d.debate.companeros.join(" · "):"Tripleta pendiente";rows=`<div class="data-row"><span>Tripleta</span><b>${esc(d.debate.nombre_tripleta||"NOVA Debate")}</b></div><div class="data-row"><span>Integrantes</span><b>${esc(names)}</b></div>`};if(area==="Staff"&&d.staff)rows=`<div class="data-row"><span>Rol</span><b>${esc(d.staff.rol||"Por asignar")}</b></div><div class="data-row"><span>Área</span><b>${esc(d.staff.area_staff||"Staff NOVA")}</b></div>`;return `<article class="module" style="--module-line:#36a9ff33;--module-soft:rgba(54,169,255,.06)"><div class="module-head"><div><div class="module-icon">${areaIcon(area)}</div><h4>${esc(area)}</h4></div><span class="muted">ACTIVA</span></div><p>${area==="MUN / ONU"?"Tu representación en Naciones Unidas.":area==="Debate"?"Tu espacio competitivo y de preparación.":area==="Artística"?"Tu dimensión creativa dentro de NOVA.":area==="Oratoria"?"Tu voz y presencia dentro del club.":"Tu rol de soporte y operación dentro de NOVA."}</p><div class="data">${rows||'<div class="data-row"><span>Estado</span><b>Integrante activo</b></div>'}</div></article>`}
async function loadActivities(){const {data}=await db.from("actividades").select("*").order("fecha",{ascending:true});const a=data||[];$("#activityCount").textContent=a.length+" actividades";$("#activityList").innerHTML=a.length?a.map(x=>`<article class="activity"><span class="tag">${esc(x.tipo||"ACTIVIDAD")} · ${esc(x.estado||"")}</span><h4>${esc(x.nombre)}</h4><p>${esc(x.descripcion||"Actividad de NOVA.")}</p><time>${x.fecha?new Date(x.fecha+"T00:00:00").toLocaleDateString("es-DO",{day:"2-digit",month:"long",year:"numeric"}):"Fecha por anunciar"}</time></article>`).join(""):"<div class='muted'>Todavía no hay actividades publicadas.</div>"}
async function loadFeedback(){if(directivaMode){$("#feedbackList").innerHTML="<div class=\"muted\">Vista de Directiva: aquí aparecería el feedback personal de un integrante.</div>";return}const {data}=await db.from("evaluaciones").select("*, actividades(nombre)").eq("integrante_id",member.id).order("fecha_evaluacion",{ascending:false});const f=data||[];$("#feedbackList").innerHTML=f.length?f.map(x=>`<article class="feedback"><strong>${esc(x.actividades?.nombre||"Evaluación NOVA")}</strong><p>${esc(x.feedback||"Evaluación registrada sin comentario.")}</p><small>${x.total!=null?esc(x.total)+ (x.maximo!=null?"/"+esc(x.maximo):" puntos"):"Feedback"} · ${x.fecha_evaluacion?new Date(x.fecha_evaluacion).toLocaleDateString("es-DO"):""}</small></article>`).join(""):"<div class='muted'>Aún no tienes feedback publicado. Cuando Directiva registre uno, aparecerá aquí.</div>"}
async function loadAchievements(){const a=[["🏛️","Primera intervención","Participación inicial en NOVA"],["🎙️","Voz NOVA","Reconocimiento por oratoria"],["🌐","Delegado NOVA","Participación en MUN"],["⚔️","Debate","Participación en debate"],["👑","Liderazgo","Reconocimiento de liderazgo"],["📋","Organizador","Participación en organización"]];$("#achievementList").innerHTML=a.map(x=>`<article class="achievement"><span class="medal">${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div></article>`).join("")}
function subscribeRealtime(){db.channel("nova-casas-live").on("postgres_changes",{event:"UPDATE",schema:"public",table:"casas"},()=>loadHouses()).subscribe()}
// No auto-login: the member portal only opens after the user submits the login form.\n// Supabase keeps the session available, but we intentionally do not boot the dashboard on page load.

// Portal navigation: every section fits inside one viewport, no page scrolling.
document.querySelectorAll('.member-nav-btn').forEach(btn=>btn.addEventListener('click',()=>{const view=btn.dataset.view;document.querySelectorAll('.portal-view').forEach(v=>v.hidden=true);const target=document.getElementById('view'+view.charAt(0).toUpperCase()+view.slice(1));if(target)target.hidden=false;document.querySelectorAll('.member-nav-btn').forEach(b=>b.classList.toggle('active',b===btn));}));
