const URL="https://hogbjrbaeedlyglegjle.supabase.co",KEY="sb_publishable_NWG23rPztabdaFhEyNtN5w_rrCeMTC5",db=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,storage:window.localStorage}});
const $=s=>document.querySelector(s), esc=s=>String(s||"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const meta={Pegaso:["🪽","#e7dfc6"],Cronos:["⏳","#4aaeff"],Fénix:["🔥","#e0b54f"],Argos:["👁️","#5fd69a"],Olimpo:["⚡","#e46e78"]};
let member=null;
async function guard(){const s=await db.auth.getSession();if(!s.data.session){location.replace("./index.html");return false}const r=await db.from("integrantes").select("*").eq("user_id",s.data.session.user.id).maybeSingle();if(!r.data){await db.auth.signOut();location.replace("./index.html");return false}member=r.data;return true}
function nav(active){const items=[["home","Inicio","⌂"],["profile","Perfil","◉"],["areas","Áreas","✦"],["activities","Actividades","◇"],["community","Feedback & logros","♢"]];$(".member-nav").innerHTML=items.map(x=>'<a class="'+(x[0]===active?"active":"")+'" href="./'+x[0]+'.html"><span>'+x[2]+'</span>'+x[1]+"</a>").join("")}
function layout(active,title,kicker){document.body.innerHTML='<div class="app"><header class="topbar"><a class="brand-small" href="./home.html"><span>N</span><b>OVA</b></a><div class="page-label"><small>'+kicker+'</small><strong>'+title+'</strong></div><div class="top-user"><div id="topAvatar">N</div><div><strong>'+esc(member.nombre_completo)+'</strong><small>'+(member.username?"@"+esc(member.username):"NOVA MEMBER")+'</small></div><button id="logoutBtn">↗</button></div></header><main class="dashboard page"></main><nav class="member-nav"></nav></div>';nav(active);$("#topAvatar").textContent=member.nombre_completo.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase();$("#logoutBtn").onclick=async()=>{await db.auth.signOut();location.replace("./index.html")}}
function empty(x){return '<div class="empty-state">'+x+"</div>"}
async function boot(active,title,kicker,render){if(await guard()){layout(active,title,kicker);await render()}}
